server:
  port: 8083

spring:
  application:
    name: person-aggregator

camel:
  component:
    http:
      connect-timeout: 5000
  context:
    tracing: false
    debugging: false
    message-history: true
    shutdown-timeout: 25
  springboot:
    use-mdc-logging: true
    main-run-controller: true


custom:
  retry:
    max-attempts: 3
    initial-interval: 1000
    max-interval: 5000
    multiplier: 2.0
    person-service:
      url: http://localhost:8081/api/persons
    address-service:
      url: http://localhost:8082/api/address

resilience4j:
  circuitbreaker:
    instances:
      personServiceCircuitBreaker:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        minimum-number-of-calls: 5
      addressServiceCircuitBreaker:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        minimum-number-of-calls: 5

soap:
  greeting:
    wsdl: http://localhost:8080/services/greeting?wsdl
    serviceClass: com.me.learning.consul.soapservice.GreetingService



logging:
  level:
    org.apache.camel: INFO
    org.me.practise.personaggregator: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [trace:%X{traceId}] [span:%X{spanId}] [correlation:%X{correlationId}] [route:%X{routeId}] %-5level %logger{36} - %msg%n"


#logging:
#    level:
#        org.apache.camel: DEBUG
#        org.apache.camel.processor.aggregate: TRACE